services:
  - type: web
    runtime: node
    name: easycheck
    plan: free
    buildCommand: cd client && npm ci --include=dev && npm run build && cd ../server && npm ci
    startCommand: cd server && node seed.js; node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://easycheck-w61z.onrender.com
